<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Obx6H6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Obx6H6/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container0Obx6H6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container0Obx6H6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container0Obx6H6\App_KernelProdContainer([
    'container.build_hash' => '0Obx6H6',
    'container.build_id' => '542c53e8',
    'container.build_time' => 1657021817,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Obx6H6');
