<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNZk1tTq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNZk1tTq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNZk1tTq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNZk1tTq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNZk1tTq\App_KernelDevDebugContainer([
    'container.build_hash' => 'NZk1tTq',
    'container.build_id' => '255da540',
    'container.build_time' => 1657020989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNZk1tTq');
