<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Achat__CLASSMETADATA__' => 0,
'App__Entity__Categorie__CLASSMETADATA__' => 1,
'App__Entity__Fournisseur__CLASSMETADATA__' => 2,
'App__Entity__GrilleTaille__CLASSMETADATA__' => 3,
'App__Entity__Matiere__CLASSMETADATA__' => 4,
'App__Entity__ProduitEntreprise__CLASSMETADATA__' => 5,
'App__Entity__ProduitFournisseur__CLASSMETADATA__' => 6,
'App__Entity__Profil__CLASSMETADATA__' => 7,
'App__Entity__Saison__CLASSMETADATA__' => 8,
'App__Entity__SousCategorie__CLASSMETADATA__' => 9,
'App__Entity__Taille__CLASSMETADATA__' => 10,
'App__Entity__Univers__CLASSMETADATA__' => 11,
'App__Entity__User__CLASSMETADATA__' => 12,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Achat',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Achat',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AchatRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'type' => [
                            'fieldName' => 'type',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'type',
                        ],
                        'dateAchat' => [
                            'fieldName' => 'dateAchat',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_achat',
                        ],
                        'quantite' => [
                            'fieldName' => 'quantite',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'quantite',
                        ],
                        'expedier' => [
                            'fieldName' => 'expedier',
                            'type' => 'boolean',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'expedier',
                        ],
                        'dateExpedition' => [
                            'fieldName' => 'dateExpedition',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'date_expedition',
                        ],
                        'statutAchat' => [
                            'fieldName' => 'statutAchat',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'statut_achat',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'type' => 'type',
                        'date_achat' => 'dateAchat',
                        'quantite' => 'quantite',
                        'expedier' => 'expedier',
                        'date_expedition' => 'dateExpedition',
                        'statut_achat' => 'statutAchat',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'type' => 'type',
                        'dateAchat' => 'date_achat',
                        'quantite' => 'quantite',
                        'expedier' => 'expedier',
                        'dateExpedition' => 'date_expedition',
                        'statutAchat' => 'statut_achat',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'achat',
                    ],
                ],
                'associationMappings' => [
                    [
                        'produit' => [
                            'fieldName' => 'produit',
                            'joinColumns' => [
                                [
                                    'name' => 'produit_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\ProduitEntreprise',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Achat',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'produit_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'produit_id' => 'produit_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'produit_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'achat_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'achat_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Categorie',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Categorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CategorieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'categorieFr' => [
                            'fieldName' => 'categorieFr',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'categorie_fr',
                        ],
                        'categorieEn' => [
                            'fieldName' => 'categorieEn',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'categorie_en',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'categorie_fr' => 'categorieFr',
                        'categorie_en' => 'categorieEn',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'categorieFr' => 'categorie_fr',
                        'categorieEn' => 'categorie_en',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'categorie',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'categorie_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'categorie_id_seq',
            ],
        ]
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Fournisseur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Fournisseur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\FournisseurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'code' => [
                            'fieldName' => 'code',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'code',
                        ],
                        'nom' => [
                            'fieldName' => 'nom',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'nom' => 'nom',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'nom' => 'nom',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'fournisseur',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'fournisseur_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'fournisseur_id_seq',
            ],
        ]
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\GrilleTaille',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\GrilleTaille',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\GrilleTailleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'grilleTaille' => [
                            'fieldName' => 'grilleTaille',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'grille_taille',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'grille_taille' => 'grilleTaille',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'grilleTaille' => 'grille_taille',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'grille_taille',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'grille_taille_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'grille_taille_id_seq',
            ],
        ]
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Matiere',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Matiere',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\MatiereRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'matiere' => [
                            'fieldName' => 'matiere',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'matiere',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'matiere' => 'matiere',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'matiere' => 'matiere',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'matiere',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'matiere_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'matiere_id_seq',
            ],
        ]
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\ProduitEntreprise',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\ProduitEntreprise',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProduitEntrepriseRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'sku' => [
                            'fieldName' => 'sku',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'sku',
                        ],
                        'dateArrivee' => [
                            'fieldName' => 'dateArrivee',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_arrivee',
                        ],
                        'dateAjout' => [
                            'fieldName' => 'dateAjout',
                            'type' => 'date',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'date_ajout',
                        ],
                        'modeAcquisition' => [
                            'fieldName' => 'modeAcquisition',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'mode_acquisition',
                        ],
                        'nomProduitFr' => [
                            'fieldName' => 'nomProduitFr',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom_produit_fr',
                        ],
                        'nomProduitEn' => [
                            'fieldName' => 'nomProduitEn',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'nom_produit_en',
                        ],
                        'descriptionFr' => [
                            'fieldName' => 'descriptionFr',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'description_fr',
                        ],
                        'descriptionEn' => [
                            'fieldName' => 'descriptionEn',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'description_en',
                        ],
                        'coupe' => [
                            'fieldName' => 'coupe',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'coupe',
                        ],
                        'entretien' => [
                            'fieldName' => 'entretien',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'entretien',
                        ],
                        'couleur' => [
                            'fieldName' => 'couleur',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'couleur',
                        ],
                        'TailleMannequin' => [
                            'fieldName' => 'TailleMannequin',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'taille_mannequin',
                        ],
                        'quantiteStock' => [
                            'fieldName' => 'quantiteStock',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'quantite_stock',
                        ],
                        'matiere1' => [
                            'fieldName' => 'matiere1',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'matiere1',
                        ],
                        'pourcentageMatiere1' => [
                            'fieldName' => 'pourcentageMatiere1',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'pourcentage_matiere1',
                        ],
                        'matiere2' => [
                            'fieldName' => 'matiere2',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'matiere2',
                        ],
                        'pourcentageMatiere2' => [
                            'fieldName' => 'pourcentageMatiere2',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'pourcentage_matiere2',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'sku' => 'sku',
                        'date_arrivee' => 'dateArrivee',
                        'date_ajout' => 'dateAjout',
                        'mode_acquisition' => 'modeAcquisition',
                        'nom_produit_fr' => 'nomProduitFr',
                        'nom_produit_en' => 'nomProduitEn',
                        'description_fr' => 'descriptionFr',
                        'description_en' => 'descriptionEn',
                        'coupe' => 'coupe',
                        'entretien' => 'entretien',
                        'couleur' => 'couleur',
                        'taille_mannequin' => 'TailleMannequin',
                        'quantite_stock' => 'quantiteStock',
                        'matiere1' => 'matiere1',
                        'pourcentage_matiere1' => 'pourcentageMatiere1',
                        'matiere2' => 'matiere2',
                        'pourcentage_matiere2' => 'pourcentageMatiere2',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'sku' => 'sku',
                        'dateArrivee' => 'date_arrivee',
                        'dateAjout' => 'date_ajout',
                        'modeAcquisition' => 'mode_acquisition',
                        'nomProduitFr' => 'nom_produit_fr',
                        'nomProduitEn' => 'nom_produit_en',
                        'descriptionFr' => 'description_fr',
                        'descriptionEn' => 'description_en',
                        'coupe' => 'coupe',
                        'entretien' => 'entretien',
                        'couleur' => 'couleur',
                        'TailleMannequin' => 'taille_mannequin',
                        'quantiteStock' => 'quantite_stock',
                        'matiere1' => 'matiere1',
                        'pourcentageMatiere1' => 'pourcentage_matiere1',
                        'matiere2' => 'matiere2',
                        'pourcentageMatiere2' => 'pourcentage_matiere2',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'produit_entreprise',
                    ],
                ],
                'associationMappings' => [
                    [
                        'sousCategorie' => [
                            'fieldName' => 'sousCategorie',
                            'joinColumns' => [
                                [
                                    'name' => 'sous_categorie_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\SousCategorie',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\ProduitEntreprise',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'sous_categorie_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'sous_categorie_id' => 'sous_categorie_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'sous_categorie_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'Univers' => [
                            'fieldName' => 'Univers',
                            'joinColumns' => [
                                [
                                    'name' => 'univers_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Univers',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\ProduitEntreprise',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'univers_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'univers_id' => 'univers_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'univers_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'taille' => [
                            'fieldName' => 'taille',
                            'joinColumns' => [
                                [
                                    'name' => 'taille_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Taille',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\ProduitEntreprise',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'taille_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'taille_id' => 'taille_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'taille_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'produit_entreprise_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'produit_entreprise_id_seq',
            ],
        ]
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\ProduitFournisseur',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\ProduitFournisseur',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProduitFournisseurRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'referenceProduit' => [
                            'fieldName' => 'referenceProduit',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'reference_produit',
                        ],
                        'anneeSortie' => [
                            'fieldName' => 'anneeSortie',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'annee_sortie',
                        ],
                        'taille' => [
                            'fieldName' => 'taille',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'taille',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'reference_produit' => 'referenceProduit',
                        'annee_sortie' => 'anneeSortie',
                        'taille' => 'taille',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'referenceProduit' => 'reference_produit',
                        'anneeSortie' => 'annee_sortie',
                        'taille' => 'taille',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'produit_fournisseur',
                    ],
                ],
                'associationMappings' => [
                    [
                        'saison' => [
                            'fieldName' => 'saison',
                            'joinColumns' => [
                                [
                                    'name' => 'saison_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Saison',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\ProduitFournisseur',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'saison_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'saison_id' => 'saison_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'saison_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'produit_fournisseur_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'produit_fournisseur_id_seq',
            ],
        ]
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Profil',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Profil',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProfilRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'libelle' => [
                            'fieldName' => 'libelle',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'libelle',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'libelle' => 'libelle',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'libelle' => 'libelle',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'profil',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'profil_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'profil_id_seq',
            ],
        ]
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Saison',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Saison',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SaisonRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'code' => [
                            'fieldName' => 'code',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'code',
                        ],
                        'saison' => [
                            'fieldName' => 'saison',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 100,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'saison',
                        ],
                        'abreviation' => [
                            'fieldName' => 'abreviation',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 2,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'abreviation',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'saison' => 'saison',
                        'abreviation' => 'abreviation',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'saison' => 'saison',
                        'abreviation' => 'abreviation',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'saison',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'saison_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'saison_id_seq',
            ],
        ]
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\SousCategorie',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\SousCategorie',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SousCategorieRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'sousCategorieFr' => [
                            'fieldName' => 'sousCategorieFr',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'sous_categorie_fr',
                        ],
                        'sousCategorieEn' => [
                            'fieldName' => 'sousCategorieEn',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'sous_categorie_en',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'sous_categorie_fr' => 'sousCategorieFr',
                        'sous_categorie_en' => 'sousCategorieEn',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'sousCategorieFr' => 'sous_categorie_fr',
                        'sousCategorieEn' => 'sous_categorie_en',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'sous_categorie',
                    ],
                ],
                'associationMappings' => [
                    [
                        'categorie' => [
                            'fieldName' => 'categorie',
                            'joinColumns' => [
                                [
                                    'name' => 'categorie_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Categorie',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SousCategorie',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'categorie_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'categorie_id' => 'categorie_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'categorie_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'sous_categorie_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'sous_categorie_id_seq',
            ],
        ]
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Taille',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Taille',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TailleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'taille' => [
                            'fieldName' => 'taille',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'taille',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'taille' => 'taille',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'taille' => 'taille',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'taille',
                    ],
                ],
                'associationMappings' => [
                    [
                        'grilleTaille' => [
                            'fieldName' => 'grilleTaille',
                            'joinColumns' => [
                                [
                                    'name' => 'grille_taille_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\GrilleTaille',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Taille',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'grille_taille_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'grille_taille_id' => 'grille_taille_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'grille_taille_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'taille_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'taille_id_seq',
            ],
        ]
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Univers',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Univers',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UniversRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'universFr' => [
                            'fieldName' => 'universFr',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'univers_fr',
                        ],
                        'UniversEn' => [
                            'fieldName' => 'UniversEn',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'univers_en',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'univers_fr' => 'universFr',
                        'univers_en' => 'UniversEn',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'universFr' => 'univers_fr',
                        'UniversEn' => 'univers_en',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'univers',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'univers_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'univers_id_seq',
            ],
        ]
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\User',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'email',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'roles',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'password',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                    ],
                ],
                'associationMappings' => [
                    [
                        'profil' => [
                            'fieldName' => 'profil',
                            'joinColumns' => [
                                [
                                    'name' => 'profil_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Profil',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\User',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'profil_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'profil_id' => 'profil_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'profil_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'user_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'user_id_seq',
            ],
        ]
    );
},

]];
