<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'cbfc25d059aeae18c70b55ec0689f6b7',
  'DATABASE_URL' => 'postgresql://root:@127.0.0.1:5432/GestionProduit?serverVersion=13&charset=utf8',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
