<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProduitEntreprise extends \App\Entity\ProduitEntreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'sku', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'dateArrivee', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'dateAjout', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'modeAcquisition', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'nomProduitFr', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'nomProduitEn', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'descriptionEn', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'coupe', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'entretien', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'couleur', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'TailleMannequin', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'quantiteStock', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'sousCategorie', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'Univers', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'matiere1', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'pourcentageMatiere1', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'matiere2', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'pourcentageMatiere2'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'sku', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'dateArrivee', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'dateAjout', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'modeAcquisition', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'nomProduitFr', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'nomProduitEn', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'descriptionFr', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'descriptionEn', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'coupe', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'entretien', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'couleur', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'TailleMannequin', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'quantiteStock', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'sousCategorie', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'Univers', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'taille', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'matiere1', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'pourcentageMatiere1', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'matiere2', '' . "\0" . 'App\\Entity\\ProduitEntreprise' . "\0" . 'pourcentageMatiere2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProduitEntreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSku(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSku', []);

        return parent::getSku();
    }

    /**
     * {@inheritDoc}
     */
    public function setSku(int $sku): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSku', [$sku]);

        return parent::setSku($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateArrivee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateArrivee', []);

        return parent::getDateArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateArrivee(\DateTimeInterface $dateArrivee): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateArrivee', [$dateArrivee]);

        return parent::setDateArrivee($dateArrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjout(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjout', []);

        return parent::getDateAjout();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjout(\DateTimeInterface $dateAjout): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjout', [$dateAjout]);

        return parent::setDateAjout($dateAjout);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeAcquisition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeAcquisition', []);

        return parent::getModeAcquisition();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeAcquisition(string $modeAcquisition): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeAcquisition', [$modeAcquisition]);

        return parent::setModeAcquisition($modeAcquisition);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProduitFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProduitFr', []);

        return parent::getNomProduitFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProduitFr(string $nomProduitFr): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProduitFr', [$nomProduitFr]);

        return parent::setNomProduitFr($nomProduitFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProduitEn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProduitEn', []);

        return parent::getNomProduitEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProduitEn(string $nomProduitEn): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProduitEn', [$nomProduitEn]);

        return parent::setNomProduitEn($nomProduitEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionFr(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionFr', []);

        return parent::getDescriptionFr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionFr(string $descriptionFr): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionFr', [$descriptionFr]);

        return parent::setDescriptionFr($descriptionFr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEn(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEn', []);

        return parent::getDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEn(string $descriptionEn): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEn', [$descriptionEn]);

        return parent::setDescriptionEn($descriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoupe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoupe', []);

        return parent::getCoupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoupe(?string $coupe): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoupe', [$coupe]);

        return parent::setCoupe($coupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntretien(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntretien', []);

        return parent::getEntretien();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntretien(?string $entretien): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntretien', [$entretien]);

        return parent::setEntretien($entretien);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouleur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouleur', []);

        return parent::getCouleur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouleur(string $couleur): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouleur', [$couleur]);

        return parent::setCouleur($couleur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleMannequin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleMannequin', []);

        return parent::getTailleMannequin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleMannequin(?string $TailleMannequin): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleMannequin', [$TailleMannequin]);

        return parent::setTailleMannequin($TailleMannequin);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantiteStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantiteStock', []);

        return parent::getQuantiteStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantiteStock(int $quantiteStock): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantiteStock', [$quantiteStock]);

        return parent::setQuantiteStock($quantiteStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousCategorie(): ?\App\Entity\SousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousCategorie', []);

        return parent::getSousCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousCategorie(?\App\Entity\SousCategorie $sousCategorie): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousCategorie', [$sousCategorie]);

        return parent::setSousCategorie($sousCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnivers(): ?\App\Entity\Univers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnivers', []);

        return parent::getUnivers();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnivers(?\App\Entity\Univers $Univers): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnivers', [$Univers]);

        return parent::setUnivers($Univers);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille(): ?\App\Entity\Taille
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille(?\App\Entity\Taille $taille): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere1', []);

        return parent::getMatiere1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere1(string $matiere1): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere1', [$matiere1]);

        return parent::setMatiere1($matiere1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPourcentageMatiere1(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPourcentageMatiere1', []);

        return parent::getPourcentageMatiere1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPourcentageMatiere1(int $pourcentageMatiere1): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPourcentageMatiere1', [$pourcentageMatiere1]);

        return parent::setPourcentageMatiere1($pourcentageMatiere1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere2', []);

        return parent::getMatiere2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere2(?string $matiere2): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere2', [$matiere2]);

        return parent::setMatiere2($matiere2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPourcentageMatiere2(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPourcentageMatiere2', []);

        return parent::getPourcentageMatiere2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPourcentageMatiere2(?int $pourcentageMatiere2): \App\Entity\ProduitEntreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPourcentageMatiere2', [$pourcentageMatiere2]);

        return parent::setPourcentageMatiere2($pourcentageMatiere2);
    }

}
