<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUveO9XB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUveO9XB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUveO9XB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUveO9XB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUveO9XB\App_KernelDevDebugContainer([
    'container.build_hash' => 'UveO9XB',
    'container.build_id' => 'bcd5a2c4',
    'container.build_time' => 1657019186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUveO9XB');
