<?php

namespace Container0Obx6H6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSousCategorieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SousCategorieRepository' shared autowired service.
     *
     * @return \App\Repository\SousCategorieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SousCategorieRepository'] = new \App\Repository\SousCategorieRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
